### ISSUE TITLE
Extra 5 K in the input Tkin?

### ISSUE THREAD

**Issue by mcyc** [GBTAmmoniaSurvey/LineFitting#19]
I noticed there's a `+5` term at the end of the following line that was retained from the earliest versions of this code. The term seems misplaced as it currently adds 5 K to the T_kin initially specified in the input. 

https://github.com/GBTAmmoniaSurvey/LineFitting/blob/6fa43e0e711cc26bebb89309007076931fcc0145/nh3_testcubes.py#L131

@low-sky, do you recall what this term was intended for?

**Comment by low-sky** [comment]
Closed by #20
