### ISSUE TITLE
Faulty noise generation

### ISSUE THREAD

**Issue by mcyc** [GBTAmmoniaSurvey/LineFitting#3]
The following lines add noise redundantly over where synthetic spectra have already been made:

https://github.com/GBTAmmoniaSurvey/LineFitting/blob/0f136c8c2a31e459c2aea4d88a74fdbd7c89abcb/nh3_testcubes.py#L148-L149

Suggestion: place these lines either outside the loop or have them modified to operate only on the current pixel.

**Comment by low-sky** [comment]
Thanks @mcyc 
Addressed in  ac609e0 ... I think
